version: '2'

services:
  db: 
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: localdb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  web:
    build: .docker/web
    ports:
       - "8080:80"
       - "4443:443"
       - "22:22"
    environment:
      PHP_SITE_NAME: dev
      PHP_HOST_NAME: localhost:80
    restart: always
    volumes:
       - ./www:/var/www
    links:
      - db
  composer: 
    build: .docker/composer
    volumes_from:
      - web
    working_dir: /var/www/public